# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# 数据文件和资源文件
datas = [
    ('data', 'data'),
    ('ui', 'ui'),
    ('services', 'services'),
    ('utils', 'utils'),
    ('controllers', 'controllers'),
    ('views', 'views'),
    ('widgets', 'widgets'),
    ('app', 'app'),
    ('cacert.pem', '.'),
]

# 隐藏导入的模块
hiddenimports = [
    'PyQt5.QtCore',
    'PyQt5.QtGui', 
    'PyQt5.QtWidgets',
    'PyQt5.QtNetwork',
    'requests',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'PIL.ImageFont',
    'json',
    'hashlib',
    'platform',
    'subprocess',
    'uuid',
    'time',
    'datetime',
    'os',
    'sys',
    'traceback',
    'threading',
    'queue',
    'urllib.parse',
    'urllib.request',
    'base64',
    'io',
    'tempfile',
    'shutil',
    'pathlib',
    'typing',
    'collections',
    'functools',
    'itertools',
    'operator',
    'copy',
    'pickle',
    'sqlite3',
    'csv',
    'configparser',
    'logging',
    'warnings',
    'inspect',
    'importlib',
    'pkgutil',
    'zipfile',
    'tarfile',
    'gzip',
    'bz2',
    'lzma',
    'zlib',
    'email',
    'html',
    'xml',
    'http',
    'ftplib',
    'smtplib',
    'poplib',
    'imaplib',
    'telnetlib',
    'socketserver',
    'xmlrpc',
    'webbrowser',
    'cgi',
    'cgitb',
    'wsgiref',
    'distutils',
    'site',
    'sysconfig',
    'pywin32',
    'win32api',
    'win32con',
    'win32gui',
    'win32process',
    'win32service',
    'win32serviceutil',
    'win32event',
    'win32file',
    'win32pipe',
    'win32security',
    'win32net',
    'win32netcon',
    'win32wnet',
    'win32clipboard',
    'win32com',
    'pythoncom',
    'pywintypes',
]

a = Analysis(
    ['main_modular.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'jupyter',
        'notebook',
        'IPython',
        'pytest',
        'unittest',
        'doctest',
        'pdb',
        'profile',
        'cProfile',
        'pstats',
        'timeit',
        'trace',
        'turtle',
        'audioop',
        'chunk',
        'colorsys',
        'imghdr',
        'sndhdr',
        'sunau',
        'wave',
        'aifc',
        'ossaudiodev',
        'winsound',
        'msilib',
        'msvcrt',
        'winreg',
        '_winapi',
        'nt',
        'posix',
        'pwd',
        'grp',
        'termios',
        'tty',
        'pty',
        'fcntl',
        'resource',
        'syslog',
        'curses',
        'readline',
        'rlcompleter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CinemaTicketSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # 设置为False隐藏控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='data/img/icon.ico' if os.path.exists('data/img/icon.ico') else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CinemaTicketSystem',
)
